version: "3"

services:
  cassandra1:
    image: cfei/cassandra
    container_name: cassandra1
    ports:
      - 9042:9042
      - 7000:7000
    environment:
      CASSANDRA_CLUSTER_NAME: "reference-cluster"
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
      CASSANDRA_BROADCAST_ADDRESS: "cassandra1"
      CASSANDRA_DATACENTER: dc1Test
      CASSANDRA_RACK: rack1Test
      CASSANDRA_STORAGE_PORT: 7000
      CASSANDRA_MAX_HEAP_SIZE: 1G
      CASSANDRA_HEAP_NEWSIZE: 200M
    restart: always

  cassandra2:
    image: cfei/cassandra
    container_name: cassandra2
    ports:
      - 9043:9042
      - 7001:7001
    environment:
      CASSANDRA_CLUSTER_NAME: "reference-cluster"
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
      CASSANDRA_BROADCAST_ADDRESS: "cassandra2"
      CASSANDRA_DATACENTER: dc1Test
      CASSANDRA_RACK: rack1Test
      CASSANDRA_STORAGE_PORT: 7001
      CASSANDRA_MAX_HEAP_SIZE: 1G
      CASSANDRA_HEAP_NEWSIZE: 200M
    restart: always

  cassandra3:
    image: cfei/cassandra
    container_name: cassandra3
    ports:
      - 9044:9042
      - 7002:7002
    environment:
      CASSANDRA_CLUSTER_NAME: "reference-cluster"
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
      CASSANDRA_BROADCAST_ADDRESS: "cassandra3"
      CASSANDRA_DATACENTER: dc1Test
      CASSANDRA_RACK: rack1Test
      CASSANDRA_STORAGE_PORT: 7002
      CASSANDRA_MAX_HEAP_SIZE: 1G
      CASSANDRA_HEAP_NEWSIZE: 200M
    restart: always
